function mockOptimizeSoliditySource(source, intent) {
  let optimized = source;

  const goal = intent.goal || '';
  // const transformations = intent.transformations || [];

  if (goal === 'minimize_gas' /* || transformations.includes('remove_sstore') */) {
    optimized = optimized.replace(
      /function setMyNumber\(uint256 _myNumber\) public \{[^}]*\}/,
      `function setMyNumber(uint256 _myNumber) public {
        // [Mock Optimization] Direct assignment without overhead
        myNumber = _myNumber;
      }`
    );
  }


  optimized = `// [Optimized Version Generated by Mock Optimizer]\n` + optimized;

  return optimized;
}

export { mockOptimizeSoliditySource };
